on:
  push:
    branches:
      - production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_KEY }}

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: build,cd-prod
          affected: 'true'
          args: '--prod'
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_BUCKET_STAGING: ${{ secrets.S3_BUCKET_STAGING }}
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
          DISTRIBUTION_ID_STAGING: ${{ secrets.DISTRIBUTION_ID_STAGING }}

